// sidebars.ts

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar for the User Documentation section
  userSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-documentation',
    },
  ],

  // Sidebar for the API Documentation section
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-documentation',
    },
  ],
};

module.exports = sidebars;
