// sidebars.ts
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import loyaltyApiSidebar from './docs/api-documentation/loyalty/sidebar';

const sidebars: SidebarsConfig = {
  // Sidebar for the User Documentation section
  userSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-documentation',
    },
  ],

  // Sidebar for the Developer Documentation section
  developerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'developer-documentation',
    },
  ],

  // Sidebar for the API Documentation section
  apiSidebar: [
    'api-documentation/intro',
    'api-documentation/loyalty/loyalty-api',
    ...loyaltyApiSidebar,
  ],
};

export default sidebars;
