// sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar for the User Documentation section
  userSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-documentation', // The name of the folder
    },
  ],

  // Sidebar for the Developer Documentation section
  developerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'developer-documentation', // The name of the folder
    },
  ],

  // Sidebar for the API Documentation section
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-documentation', // The name of the folder
    },
  ],
};

module.exports = sidebars;